# 命令行全写在这
cmd:
  cmd1: cd /cygdrive/d/workspace/tmp_files && unzip -o PBackRelease.zip -d /cygdrive/d/workspace/PortalWeb/bin  # portalback
  cmd2: unzip -o /cygdrive/d/workspace/tmp_files/ABackRelease.zip -d /cygdrive/d/workspace/AppWeb-B-8085/bin >> log.txt  # appback
  cmd3: ls

# 各种路径写在这
path:
  portal_back_path: D:\Source\Portal-BackEnd
  portal_sln_path: D:\Source\Portal-BackEnd\dotnet_xrm\ServiceOne-Portal.sln
  portal_dll_path: D:\Source\Portal-BackEnd\dotnet_xrm\\bin
  portal_dll_tmp_path: D:\Source\\tmp_files\portal_dll
  tmp_files_path: D:\Source\\tmp_files
  portal_back_src_path: D:\Source\\tmp_files\\PBackRelease.zip
  portal_back_dst_path: /cygdrive/d/workspace/tmp_files/PBackRelease.zip
  app_back_path: D:\Source\APP-BackEnd
  app_sln_path: D:\Source\APP-BackEnd\DotNetSource\RekTec.Xmobile.sln
  app_dll_path: D:\Source\APP-BackEnd\DotNetSource\\bin
  app_tmp_path: D:\Source\\tmp_files\mobile_dll
  app_back_src_path: D:\Source\\tmp_files\\ABackRelease.zip
  app_back_dst_path: /cygdrive/d/workspace/tmp_files/ABackRelease.zip


# dll文件写在这
dll:
  app:
    - RekTec.Xmobile.Biz.Service.dll
    - RekTec.Xmobile.Biz.dll
    - RekTec.Xmobile.Model.dll
    - RekTec.Xmobile.Service.WebApi.dll
    - RekTec.XStudio.FileStorage.PortalDBFileSystem.dll
  portal:
    - RekTec.XStudio.Crm.WebApi.dll
    - RekTec.XStudio.Exam.WebApi.dll
    - RekTec.XStudio.Expense.Biz.dll
    - RekTec.XStudio.Exam.WebApi.dll
    - RekTec.XStudio.Parts.WebApi.dll
    - RekTec.XStudio.Public.WebApi.dll
    - RekTec.XStudio.Service.Biz.dll
    - RekTec.XStudio.Service.WebApi.dll
    - RekTec.XStudio.Station.WebApi.dll
    - RekTec.XStudio.Station.Biz.dll